name: Andres-Build-VIP
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: target/setup-theos@v1
      - name: Build
        run: make package FINALPACKAGE=1
        env:
          THEOS:  ${{github.workspace}}/theos
      - uses: actions/upload-artifact@v4
        with:
          name: Andres-VIP-DEB
          path: packages/*.deb
